### ISSUE TITLE
mingw link in readme is dead

### ISSUE THREAD

**Issue by torgeros** [ConcoctLang/concoct#20]
the link to mingw.org in [the readme file](https://github.com/ConcoctLang/concoct/blob/master/.github/README.md) is dead.

is suggest linking to wikipedia (https://en.wikipedia.org/wiki/MinGW) or OSDN (https://osdn.net/projects/mingw/) instead

**Comment by ldilley** [comment]
Thank you for bringing this to our attention, @torgeros. It looks like the domain registrant of "mingw.org" let it lapse according to https://www.reddit.com/r/cpp/comments/kuyqz1/mingworg_is_down/. It has been nearly a month. We'll use the OSDN link. An update to `README.md` is incoming shortly...
